name: Update Rain

on:
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:

jobs:
  update:
    name: Update Rain
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Clone ${{ github.repository }}
        uses: actions/checkout@v7
      
      - name: Set Up uv
        uses: astral-sh/setup-uv@v10.2.0

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_CLIENT_ID }}
          audience: ${{ secrets.TS_AUDIENCE }}
          tags: tag:github-actions
          ping: seika
      
      - name: Download AltServer
        run: |
          curl -fsSLO --retry 5 --retry-delay 5 https://files.seika.computer/altserver.zip
          unzip altserver.zip -d altserver
      
      - name: Get Rain IPA URL
        id: url
        shell: uvx xonsh {0}
        run: |
          import json
          import os

          assets = json.loads($(gh release view --json assets))["assets"]
          url = next(asset["url"] for asset in assets if asset["name"] == "RainTweak.ipa")

          print(f"url={url}", file=open(os.getenv("GITHUB_OUTPUT"), "a"))
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ra1ncord/RainTweak
      
      - name: Download Rain
        run: curl -fsSLO ${{ steps.url.outputs.url }}
      
      - name: Update AltSource (altsource CLI)
        run: | 
          altserver/AltServer.app/Contents/MacOS/altsource update altsource.json \
          --ipa RainTweak.ipa \
          --version-download-url ${{ steps.url.outputs.url }} \
          --app-name Rain \
          --app-developer "Discord Inc. and Rain contributors" \
          --app-subtitle "A Discord client mod for mobile" \
          --app-description "Rain is a Discord client mod for mobile.\n\n For more information, visit Rain's repository: https://codeberg.org/raincord/rain" \
          --app-tint-color "#5865F2" \
          --app-category social \
      
      - name: Update AltSource (Manual)
        shell: uv run --with httpx2 {0}
        run: |
          import json
          from pathlib import Path

          import httpx2 as httpx

          altsource_file = Path("altsource.json")
          altsource = json.loads(altsource_file.read_text())

          app = altsource["apps"][-1]
          itunes_metadata = httpx.get("https://itunes.apple.com/lookup?bundleId=com.hammerandchisel.discord").raise_for_status().json()["results"][0]

          app["iconURL"] = itunes_metadata["artworkUrl100"]
          
          screenshots = altsource["apps"][-1]["screenshots"]
          screenshots["iphone"] = itunes_metadata["screenshotUrls"]
          screenshots["ipad"] = itunes_metadata["ipadScreenshotUrls"]

          altsource_file.write_text(json.dumps(altsource))
      
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v8
        with:
          add-paths: altsource.json
          sign-commits: true
      
      - name: Merge Pull Request
        if: ${{ steps.pr.outputs.pull-request-number }}
        run: gh pr merge --squash ${{ steps.pr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ github.token }}